# -*- coding: utf-8 -*-
{
    "name": "POS Z Report || POS Session Report || POS Session Z Report || Session Cash In Out",
    "author": "OMAX Informatics",
    "version": "13.0.1.0",
    "website": "https://www.omaxinformatics.com",
    "category": "Point Of Sale",
    'summary': """
        Z Report,
        POS Z Receipt,
        POS Session Receipt,
        POS Session Z Receipt,
        POS Z Report,
        POS Session Report,
        POS Session Z Report,
        Session Report,
        Point Of Sale Session Report,
        Session Receipt,
        Category Wise Sales,
        POS Session Taxes Detail,
        Session Taxes Detail,
        Session Pricelist Detail,
        Pricelist Detail,
        POS Session Pricelist Detail,
        POS Payment Detail,
        Payment Detail,
        Point Of Sale Payment Detail,
        Point Of Sale Cash In Out,
        Point Of Sale Cash In-Out,
        Point Of Sale Cash In/Out,
        POS Cash In Out,
        POS Cash In-Out,
        POS Cash In/Out,
        POS Cash In Out Receipt,
        POS Cash In-Out Receipt,
        POS Cash In/Out Receipt,
        POS Cash In Out Report,
        POS Cash In-Out Report,
        POS Cash In/Out Report,
        POS Cash Control,
        Point Of Sale Cash Control,
        Cash Control Report,
        Pos Cash In Out - Odoo,
        Put Money In,
        Take Money Out,
	""",
    'description': """
    	POS Z Report || POS Session Report || POS Session Z Report
    """,
    "depends": [
        "base",
        "point_of_sale",
    ],
    "data": [
        "views/templates.xml",
        "report/report_pos_session.xml",
        "views/pos_session_view.xml",
    ],
    'demo': [],
    'test':[],
    "images": ["static/description/banner.jpg",],
    'license': 'AGPL-3',
    'currency':'USD',
    'price': 30.0,
    'qweb': [
        'static/src/xml/pos_session_report.xml',
    ],
    "installable": True,
    "auto_install": False,
    "application": True,
}
